#include "../Source/AtomicScaleBuilder.h"
#include "../Source/ElementSpectralData.h"

#include <array>
#include <cstdint>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <string>
#include <vector>

namespace
{
    using Builder = AtomicScaleBuilder;

    struct ModeSpec
    {
        const char* name;
        Builder::ScaleMode builderMode;
        int maxDegrees;
        double minSeparationCents;
    };

    // The first four rows retain the original Atomic Scale presets. Raw is
    // bounded to the 128 strongest source-line representatives so it remains a
    // useful MIDI map rather than a several-thousand-step analysis dump.
    constexpr std::array<ModeSpec, 5> modes {{
        { "Core",        Builder::ScaleMode::Melodic,      7, 80.0 },
        { "Extended",    Builder::ScaleMode::Performable, 12, 40.0 },
        { "Microtonal",  Builder::ScaleMode::Microtonal,  24, 20.0 },
        { "Scientific",  Builder::ScaleMode::Scientific,  48, 10.0 },
        { "Raw 128",     Builder::ScaleMode::Scientific, 128,  0.0 },
    }};

    struct SetInfo
    {
        std::uint32_t offset = 0;
        std::uint16_t count = 0;
        double referenceWavelengthNm = 0.0;
    };

    std::string escaped (const char* value)
    {
        std::string result;
        for (const char* p = value; p != nullptr && *p != '\0'; ++p)
        {
            if (*p == '\\' || *p == '"')
                result.push_back('\\');
            result.push_back(*p);
        }
        return result;
    }
}

int main (int argc, char** argv)
{
    if (argc != 2)
    {
        std::cerr << "usage: GenerateAtomicScaleCatalog <output-header>\n";
        return 2;
    }

    const int elementCount = ElementSpectralData::numSupportedElements();
    if (elementCount <= 0)
    {
        std::cerr << "no element spectral data\n";
        return 3;
    }

    std::vector<double> cents;
    std::vector<SetInfo> sets;
    sets.reserve((std::size_t) elementCount * modes.size());

    for (int element = 0; element < elementCount; ++element)
    {
        for (const auto& mode : modes)
        {
            Builder::Options options;
            options.elementName = ElementSpectralData::nameForElement(element);
            options.rootHz = 440.0;
            options.scaleMode = mode.builderMode;
            options.maxScaleDegrees = mode.maxDegrees;
            options.minSeparationCents = mode.minSeparationCents;
            options.representativeMode = Builder::RepresentativeMode::Medoid;
            options.alwaysIncludeRoot = true;

            const auto result = Builder::buildPlayableAtomicScale(
                ElementSpectralData::linesForElement(element), options);

            SetInfo info;
            info.offset = (std::uint32_t) cents.size();
            info.count = (std::uint16_t) std::min<std::size_t>(result.scaleDegrees.size(), 128);
            info.referenceWavelengthNm = result.lambdaRefNm;
            sets.push_back(info);

            for (std::size_t i = 0; i < info.count; ++i)
                cents.push_back(result.scaleDegrees[i].cents);
        }
    }

    std::ofstream out(argv[1], std::ios::binary | std::ios::trunc);
    if (! out)
    {
        std::cerr << "cannot open output: " << argv[1] << "\n";
        return 4;
    }

    out << "// Generated by tools/GenerateAtomicScaleCatalog.cpp. Do not edit by hand.\n"
           "#pragma once\n\n"
           "#include <array>\n"
           "#include <cstdint>\n\n"
           "namespace AtomicScaleCatalogData\n"
           "{\n"
           "    inline constexpr int numElements = " << elementCount << ";\n"
           "    inline constexpr int numModes = " << modes.size() << ";\n\n"
           "    struct SetInfo\n"
           "    {\n"
           "        std::uint32_t offset;\n"
           "        std::uint16_t count;\n"
           "        double referenceWavelengthNm;\n"
           "    };\n\n";

    out << "    inline constexpr std::array<const char*, numElements> elementSymbols {{\n";
    for (int element = 0; element < elementCount; ++element)
        out << "        \"" << escaped(ElementSpectralData::symbolForElement(element)) << "\""
            << (element + 1 == elementCount ? "\n" : ",\n");
    out << "    }};\n\n";

    out << "    inline constexpr std::array<const char*, numElements> elementNames {{\n";
    for (int element = 0; element < elementCount; ++element)
        out << "        \"" << escaped(ElementSpectralData::nameForElement(element)) << "\""
            << (element + 1 == elementCount ? "\n" : ",\n");
    out << "    }};\n\n";

    out << "    inline constexpr std::array<const char*, numModes> modeNames {{\n";
    for (std::size_t mode = 0; mode < modes.size(); ++mode)
        out << "        \"" << modes[mode].name << "\""
            << (mode + 1 == modes.size() ? "\n" : ",\n");
    out << "    }};\n\n";

    out << "    inline constexpr std::array<SetInfo, numElements * numModes> sets {{\n";
    out << std::setprecision(12);
    for (std::size_t i = 0; i < sets.size(); ++i)
    {
        const auto& set = sets[i];
        out << "        SetInfo { " << set.offset << "u, " << set.count << "u, "
            << set.referenceWavelengthNm << " }"
            << (i + 1 == sets.size() ? "\n" : ",\n");
    }
    out << "    }};\n\n";

    out << "    inline constexpr std::array<double, " << cents.size() << "> cents {{\n";
    for (std::size_t i = 0; i < cents.size(); ++i)
        out << "        " << cents[i] << (i + 1 == cents.size() ? "\n" : ",\n");
    out << "    }};\n"
           "}\n";

    if (! out.good())
    {
        std::cerr << "failed while writing output\n";
        return 5;
    }

    std::cout << "generated " << elementCount << " elements x " << modes.size()
              << " modes, " << cents.size() << " degrees\n";
    return 0;
}
